language: objective-c
#before_script:
#    - sudo easy_install cpp-coveralls
#    - sudo easy_install PyYAML
xcode_workspace: LibPhoneNumberSwift.xcworkspace
xcode_scheme: LibPhoneNumberSwift
xcode_sdk: macosx
xctool_args: GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
    - ./coveralls.rb -x swift -e LibPhoneNumberSwiftTests
